version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    volumes:
      - ./homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    user: $PUID:$PGID
    network_mode: host
    devices:
      - /dev/ttyACM0:/dev/ttyACM0

  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt:latest
    volumes:
      - ./zigbee2mqtt/:/app/data
#      - /run/udev:/run/udev:ro
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    restart: always
#    user: $PUID:$PGID
    privileged: true
    restart: unless-stopped
    environment:
      - TZ=$TZ
    network_mode: host
